//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика_задание2
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_draft
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string header { get; set; }
        public string article { get; set; }
        public string author { get; set; }
        public bool publish { get; set; }
    }
}
